language: node_js
node_js:
  - "9"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script: 
  - npm install -g @angular/cli

script:
  - ng build --prod --base-href https://rahmanfasalu.github.io/travis-demo/

 deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/travis-demo
  on:
    branch: master
    
